# Generated by Django 4.1.4 on 2022-12-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slutasnusa', '0003_slutasnusaitem_quitdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlutaSnusaItem',
        ),
    ]
